### ISSUE TITLE
polymer init is not working

### ISSUE THREAD

**Issue by xintellion** [Polymer/app-drawer-template#1]
When I try to run "polymer init" and choose the app-drawer-template I get the following.
polymer init 
? Which starter template would you like to use? app-drawer-template
info:    Running template app-drawer-template
info:    Downloading latest release of Polymer/app-drawer-template

I'm all done. Running bower install for you to install the required dependencies. If this fails, try running the command yourself.

bower                           ENOENT No bower.json present

**Comment by rockaut** [comment]
as a workaround just clone it with git and do a bower update

**Comment by xintellion** [comment]
Yes that's exactly what I did. Thx

**Comment by RyanCopley** [comment]
came here to report the same thing.. considering this is in the official polymer documentation maybe this should be fixed sooner rather than later?

**Comment by CaptainCodeman** [comment]
I think it's all very new and nothing more than minor teething issues. New site and docs look great and new example apps are very useful. :thumbsup:

**Comment by tograd** [comment]
teething issue doesn't matter. it's the main starter guide for everyone. it needs to be fixed asap

**Comment by ketile** [comment]
After cloning the repository and running `bower update` the documentation works until the `polymer build` command. This fails on Windows 7 (power shell and git bash) due to a duplication of paths. What should be 

`c:\repos\application-software\app-drawer-template` 

becomes 

`c:\repos\application-software\app-drawer-template\repos\application-software\app-drawer-template\`

**Comment by kevinpschaaf** [comment]
This was an issue in the CLI, which should be resolved now.

Please try `npm install -g polymer-cli`, and it should work now.  Sorry for the confusion.

**Comment by ncrawlins** [comment]
do I need to use a nightly build or something?  This template still does not work on Windows 10. with version 0.8.0 of the cli.

**Comment by prumbles** [comment]
I just installed everything for the first time tonight, and I am getting the "no bower.json" error as well.  I'm using Windows 10.  Updated node/npm to the latest as well, and still not working.  Works fine on my Macbook though.

**Comment by ketile** [comment]
Get the same error as @prumbles on Windows 7 for both `app-drawer-template` and `shop`. Tested with Node v4.4.4 and v6.2.0 

@kevinpschaaf Would you consider re-opening this issue?

**Comment by kevinpschaaf** [comment]
Re-opening, appears to be CLI issues on Windows.

**Comment by kevinpschaaf** [comment]
@justinfagnani is this known on the `polymer-cli` repo?

**Comment by ncrawlins** [comment]
I think issue https://github.com/Polymer/polymer-cli/issues/181 on polymer-cli once fixed, will fix this

**Comment by LasaleFamine** [comment]
Windows 10 and Node v6.2.0 here, same problem, `app-drawer-template` and `shop template` not working.
I also get the erros below when I try to start with the `blank application template` and `element template`:

```
error:   Uncaught exception: TypeError: this.opts.filename.replace is not a function
error:   TypeError: this.opts.filename.replace is not a function
```

**Comment by fraserhore** [comment]
I'm getting: 

module.js:341
    throw err;
    ^

Error: Cannot find module '..'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at C:\Users\Fraser\AppData\Roaming\npm\node_modules\polymer-cli\bin\polymer.js:19:36
    at C:\Users\Fraser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\resolve\lib\async.js:46:14
    at process (C:\Users\Fraser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\Fraser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\Fraser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\Fraser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\resolve\lib\async.js:92:31)

**Comment by jfrazzano** [comment]
@fraserhore hit same and more issues till I opened folder and checked for files and manually updated

Still only have upgrade on one system.  If you have the time and inclination, can you see the actual files in the folder? 

The windows ten system it worked on I could see them.  I know it sounds like a dopey q, but if you can and you're still having the issue it will save me and likely others from trying something that is actually an issue. 

If you can't see them, I will make the effort to put files in right files on 7, and 10 and report back. Thank. 

And Kevin, 

Thanks again for the tireless--I know for you usual--work. 

The last 6 months of polymer have been amazing.
